### ISSUE TITLE
BGM doesn't load sometimes when launching the game.

### ISSUE THREAD

**Issue by MelonBoyy** [potatoes1286/TNH-BGMLoader#12]
Every other bank like announcer voices still work while background music doesn't work sometimes. I think it might be based on how many mods you have or if you get to tnh before all items are finished loading, i'm not sure. I just know that this happens sometimes.

**Comment by potatoes1286** [comment]
interesting. can you see if it's possible to replicate this?
maybe try waiting a minute before going to TnH and seeing if it doesn't happen, then compare if you rush into starting a TnH game as fast as possible.

**Comment by THISACCCOUNT** [comment]
I think it matters how fast you get into tnh from when the game launches. I immediately ran to play tnh when I was able to move and the songs worked. It didn't work after caching was complete before I got into tnh though.

**Comment by potatoes1286** [comment]
so, if i understand
running as fast as possible into TnH then starting a game -> worked
waiting for TnH tweaker caching to complete then starting a game -> didn't work?

**Comment by THISACCCOUNT** [comment]
I use Virtual Desktop so I don't know if this happens to everyone but I think I found it out!

So I normally get off of vr when the game is loading so I can do other stuff while it's doing it's own thing. That causes my pc to start using it's speakers instead of my headset speakers. The music might be stuck playing on my pc speakers instead because of that.

**Comment by potatoes1286** [comment]
Ho. Sorry, i never ended up seeing the comment.
But good to hear it got fixed!
